### ISSUE TITLE
Error when trying to access the dag menu

### ISSUE THREAD

**Issue by andrionbecker** [patcorwin/fossil#9]
I get this error when trying to access the dag menu in maya 2019. I'm pretty sure I followed the directions correctly
# Error: WindowsError: file C:/Users/Archanex/Documents/maya/scripts\pdil\melOverrides\dagMenuProc.py line 63: 3 #

**Comment by patcorwin** [comment]
I think I fixed it in the latest, I suspect you have an invalid folder listed in the place maya looks for mel scripts so now I'm guarding against that.  If it doesn't work, in the script editor, can you make sure line numbers and stack trace is turned on and try again?  They're in the `History` menu of the script editor.  Hopefully this will print out some more info.
![image](https://user-images.githubusercontent.com/10981431/56265933-c7d1e900-609f-11e9-8caa-9fc0411bdc85.png)

Also, if you could, in python run:

```
import os
print( os.environ['maya_script_path'] )
```
Reopen and add the addition info if needed.

**Comment by andrionbecker** [comment]
![screenShot](https://user-images.githubusercontent.com/17692877/56476073-7e92e800-6457-11e9-862b-630485cdcda9.jpg)

I ran the python code you posted and it spit out a list of directories, for your convenience I split them out so that each was on its own line, but in the original printout it put them all on a single line. Anyway, I no longer get an error at least, but I still don't see any IK/FK switch options when I select a control and right click. I've attached a screenshot for your reference
